filetype on
filetype plugin indent on

set number
set cursorline

set linebreak
set wrap

syntax on
set cc=80
set tabstop=8
set autoindent

set clipboard+=unnamedplus

set list
set listchars=eol:⏎,space:·,tab:▸\ ,nbsp:⎵

colorscheme zellner
